= Hope Evangelical Lutheran Church Missouri Synod

In the name of the Father, and of the Son, and of the Holy Spirit, Amen.

== Preamble

Recognizing our unity in Christ and our common practice in the Christian faith; desiring to express our fellowship in worship and work; knowing our spiriual needs; mindful of our Christian priviliges and duties, and wishing to observe orderly cooperation, we adopt the following constitution:

== ARTICLE I - NAME AND INCORPORATION

The name of the congregation shall be Hope Evangelical Lutheran Church. The congregation shall be incorporated under the laws of the state of Ohio.

== ARTICLE II - CONFESSION OF FAITH

The congregation accepts all the canonical books of the Old and New Testaments as a whole and in all their parts as the divinely inspired, revealed, and inerrant Word of God and submits to this as the only infallible authority in all matters of faith and life. As brief and true statements of the doctrines of the Word of God, the congregation accepts and confesses the following Symbols, subscription to which shall be required of all its members: (1) the ancient ecumenical Creeds the Apostolic, the Nicene, and the Athanasian; (2) the Unaltered Augsburg Confession and Luther's Small Catechism. As further elaboration of and in accord with these Lutheran Symbols, the congregation also receives the other documents in the Book of Concord of 1580: the Apology, Luther's Large Catechism, the Smalcald Articles and the Formula of Concord; and recognizes them as normative for its theology. The congretation accepts without reservation the symbolical books of the evangelical Lutheran Church, not insofar as, but because they are the presentation and explanation of the pure doctrine of the Word of God and a summary of the faith of the evangelical Lutheran Church.

== ARTICLE III - PURPOSE

The purpose of the congregation shall be to proclaim and propagate the Christian faith through the Means of Grace.

== ARTICLE IV - POWERS

. All power in the congregation has its source in the Word of God, which is the norm for its faith and life. All individuals and groups within the congregation shall submit to the authority of the Word; and the life and activity of the congregation and its organizations shall conform to it.
. In all matters left undecided in Holy Writ and not subject to civil laws, the congregation itself, in accordance with this constitution, and not any individual or group within it, or synod, shall have the right of ultimate decision.
. The powers of the congregation shall be vested in the congregation meeting called and conducted in such manner as is provided in this constitution, and, to the extent conveyed by this constitution or as assigned from time to time by the congregation meeting, in the boards elected by the congregation.
. All schools, societies, groups and organizations within the church and identified with our congregation must be organized with the consent of the majority of members present at a legally called congregation meeting and labor under the guidance of church council, also empowered by the congregation.
. In fulfillment of its purposes the congregation is empowered to:
.. acquire real and personal property by gifts, devise, bequest, purchase, or other lawful means;
.. hold title to and use its property for any and all activities consistent with its purpose;
.. sell, mortgage, lease, transfer, or otherwise dispose of its property by any lawful means;
.. enter into contract;
.. sue and be sued;
.. elect officers and boards for the exercise of their powers and authority and require the to conduct their affairs in accordance with this constitution and its bylaws, and the resolutions of the congregation.
. Real property shall not be purchased, disposed of, or encumbered in any manner except by resolution adopted by not less than a two-thirds majority ballot vote of the members present and voting at a legally called meeting of the congregation.
. Should the congregation cease to do business and be dissolved, all property and funds remaining after the payment of the debts of the congregation shall be distributed to a corporation trust, foundation, or other organization organized and existing for religious and/or charitable purposes which would then qualify under the provisions of section 501 (e) (3) of the Internal Revenue Code, as now enacted or as may hereafter be amended.

== ARTICLE V - MEMBERSHIP IN THE CONGREGATION

. Members of the congregation shall be those who are designated as such at the time that this constitution is adopted, and those who are admitted thereafter; and who maintain their membership in accordance with the provisions of this constitution and its bylaws. There shall be no membership restrictions with respect to race, color, national origin or sex.
. Members shall be classified as (a) baptized; (b) communicant, but unconfirmed; (c) confirmed; (d) voting.
.. Baptized members are those persons who have been received by the Sacrament of Holy Baptism in this congregation, or having been previously baptized in the mane of the Triune God, haave been received by proper transfer from other congregations or by affirmation of faith.
.. Communicant, but unconfirmed members are those who have received training in the meaning and practice of the Lord's Supper and who participate in Communion but who have not yet been confirmed.
.. Confirmed members are baptized persons who have been confirmed in this congregation, those who have been received by adult Baptism, or by transfer as confirmed members from other congregation, or baptized persons received by affirmation of faith.
.. Voting members shall be those who are confirmed members in good standing, as provided by the bylaws.
. It shall be the privilege and duty of members of this congregation to:
.. make diligent use of the Means of Grace, both Word and Sacraments;
.. life a Christian life in accordance with the Word of God and the teachings of the Lutheran Church;
.. support the work of the congregation.

== ARTICLE VI - DISCIPLINE

. A member who advocates doctrines which are contrary to the Holy Scripture and the Confessions of the Church, or who is guilty of conduct that is grossly unbecoming a member of the Body of Christ, shall be subject to discipline.
. Discipline shall be administered by the church council on behalf of the congregation, in consultation with the board of elders as indicated in the bylaws. Following the church council's action, the individual has the right of appeal to the congregation.

