= Hope Evangelical Lutheran Church Missouri Synod

In the name of the Father, and of the Son, and of the Holy Spirit, Amen.

== Preamble

Recognizing our unity in Christ and our common practice in the Christian faith; desiring to express our fellowship in worship and work; knowing our spiriual needs; mindful of our Christian priviliges and duties, and wishing to observe orderly cooperation, we adopt the following constitution:

== ARTICLE I - NAME AND INCORPORATION

The name of the congregation shall be Hope Evangelical Lutheran Church. The congregation shall be incorporated under the laws of the state of Ohio.

== ARTICLE II - CONFESSION OF FAITH

The congregation accepts all the canonical books of the Old and New Testaments as a whole and in all their parts as the divinely inspired, revealed, and inerrant Word of God and submits to this as the only infallible authority in all matters of faith and life. As brief and true statements of the doctrines of the Word of God, the congregation accepts and confesses the following Symbols, subscription to which shall be required of all its members: (1) the ancient ecumenical Creeds the Apostolic, the Nicene, and the Athanasian; (2) the Unaltered Augsburg Confession and Luther's Small Catechism. As further elaboration of and in accord with these Lutheran Symbols, the congregation also receives the other documents in the Book of Concord of 1580: the Apology, Luther's Large Catechism, the Smalcald Articles and the Formula of Concord; and recognizes them as normative for its theology. The congretation accepts without reservation the symbolical books of the evangelical Lutheran Church, not insofar as, but because they are the presentation and explanation of the pure doctrine of the Word of God and a summary of the faith of the evangelical Lutheran Church.

== ARTICLE III - PURPOSE

The purpose of the congregation shall be to proclaim and propagate the Christian faith through the Means of Grace.

== ARTICLE IV - POWERS

. All power in the congregation has its source in the Word of God, which is the norm for its faith and life. All individuals and groups within the congregation shall submit to the authority of the Word; and the life and activity of the congregation and its organizations shall conform to it.
. In all matters left undecided in Holy Writ and not subject to civil laws, the congregation itself, in accordance with this constitution, and not any individual or group within it, or synod, shall have the right of ultimate decision.
. The powers of the congregation shall be vested in the congregation meeting called and conducted in such manner as is provided in this constitution, and, to the extent conveyed by this constitution or as assigned from time to time by the congregation meeting, in the boards elected by the congregation.
. All schools, societies, groups and organizations within the church and identified with our congregation must be organized with the consent of the majority of members present at a legally called congregation meeting and labor under the guidance of church council, also empowered by the congregation.

