= Hope Evangelical Lutheran Church Missouri Synod

In the name of the Father, and of the Son, and of the Holy Spirit, Amen.

== Preamble

Recognizing our unity in Christ and our common practice in the Christian faith; desiring to express our fellowship in worship and work; knowing our spiriual needs; mindful of our Christian priviliges and duties, and wishing to observe orderly cooperation, we adopt the following constitution:

== ARTICLE I - NAME AND INCORPORATION

The name of the congregation shall be Hope Evangelical Lutheran Church. The congregation shall be incorporated under the laws of the state of Ohio.

== ARTICLE II - CONFESSION OF FAITH

The congregation accepts all the canonical books of the Old and New Testaments as a whole and in all their parts as the divinely inspired, revealed, and inerrant Word of God and submits to this as the only infallible authority in all matters of faith and life. As brief and true statements of the doctrines of the Word of God, the congregation accepts and confesses the following Symbols, subscription to which shall be required of all its members: (1) the ancient ecumenical Creeds the Apostolic, the Nicene, and the Athanasian; (2) the Unaltered Augsburg Confession and Luther's Small Catechism. As further elaboration of and in accord with these Lutheran Symbols, the congregation also receives the other documents in the Book of Concord of 1580: the Apology, Luther's Large Catechism, the Smalcald Articles and the Formula of Concord; and recognizes them as normative for its theology. The congretation accepts without reservation the symbolical books of the evangelical Lutheran Church, not insofar as, but because they are the presentation and explanation of the pure doctrine of the Word of God and a summary of the faith of the evangelical Lutheran Church.

== ARTICLE III - PURPOSE

The purpose of the congregation shall be to proclaim and propagate the Christian faith through the Means of Grace.

== ARTICLE IV - POWERS

. All power in the congregation has its source in the Word of God, which is the norm for its faith and life. All individuals and groups within the congregation shall submit to the authority of the Word; and the life and activity of the congregation and its organizations shall conform to it.
. In all matters left undecided in Holy Writ and not subject to civil laws, the congregation itself, in accordance with this constitution, and not any individual or group within it, or synod, shall have the right of ultimate decision.
. The powers of the congregation shall be vested in the congregation meeting called and conducted in such manner as is provided in this constitution, and, to the extent conveyed by this constitution or as assigned from time to time by the congregation meeting, in the boards elected by the congregation.
. All schools, societies, groups and organizations within the church and identified with our congregation must be organized with the consent of the majority of members present at a legally called congregation meeting and labor under the guidance of church council, also empowered by the congregation.
. In fulfillment of its purposes the congregation is empowered to:
.. acquire real and personal property by gifts, devise, bequest, purchase, or other lawful means;
.. hold title to and use its property for any and all activities consistent with its purpose;
.. sell, mortgage, lease, transfer, or otherwise dispose of its property by any lawful means;
.. enter into contract;
.. sue and be sued;
.. elect officers and boards for the exercise of their powers and authority and require the to conduct their affairs in accordance with this constitution and its bylaws, and the resolutions of the congregation.
. Real property shall not be purchased, disposed of, or encumbered in any manner except by resolution adopted by not less than a two-thirds majority ballot vote of the members present and voting at a legally called meeting of the congregation.
. Should the congregation cease to do business and be dissolved, all property and funds remaining after the payment of the debts of the congregation shall be distributed to a corporation trust, foundation, or other organization organized and existing for religious and/or charitable purposes which would then qualify under the provisions of section 501 (e) (3) of the Internal Revenue Code, as now enacted or as may hereafter be amended.

== ARTICLE V - MEMBERSHIP IN THE CONGREGATION

. Members of the congregation shall be those who are designated as such at the time that this constitution is adopted, and those who are admitted thereafter; and who maintain their membership in accordance with the provisions of this constitution and its bylaws. There shall be no membership restrictions with respect to race, color, national origin or sex.
. Members shall be classified as (a) baptized; (b) communicant, but unconfirmed; (c) confirmed; (d) voting.
.. Baptized members are those persons who have been received by the Sacrament of Holy Baptism in this congregation, or having been previously baptized in the mane of the Triune God, haave been received by proper transfer from other congregations or by affirmation of faith.
.. Communicant, but unconfirmed members are those who have received training in the meaning and practice of the Lord's Supper and who participate in Communion but who have not yet been confirmed.
.. Confirmed members are baptized persons who have been confirmed in this congregation, those who have been received by adult Baptism, or by transfer as confirmed members from other congregation, or baptized persons received by affirmation of faith.
.. Voting members shall be those who are confirmed members in good standing, as provided by the bylaws.
. It shall be the privilege and duty of members of this congregation to:
.. make diligent use of the Means of Grace, both Word and Sacraments;
.. life a Christian life in accordance with the Word of God and the teachings of the Lutheran Church;
.. support the work of the congregation.

== ARTICLE VI - DISCIPLINE

. A member who advocates doctrines which are contrary to the Holy Scripture and the Confessions of the Church, or who is guilty of conduct that is grossly unbecoming a member of the Body of Christ, shall be subject to discipline.
. Discipline shall be administered by the church council on behalf of the congregation, in consultation with the board of elders as indicated in the bylaws. Following the church council's action, the individual has the right of appeal to the congregation.
. Discipline in the congregation shall be exercised in accordance with Matthew 18:15-18.

== ARTICLE VII - WORSHIP

As an expression of the unity of the church in Christ the congregation recognizes the desirability of conforming to the practices of other Lutheran congregations.

== ARTICLE VIII - THE PASTOR

. A pastor of the congregation shall be a person whose soundness in the faith, aptness to teach, and educational qualifications have been examined and approved by the Church, and who has been properly ordained; who accepts and adheres to the Confession of Faith of the congregation; and who strives in life and conduct to be above reproach.
. Authority to call a pastor shall rest in the congregation. Such authority to call shall be exercised by not less than a two-thirds majority ballot vote of members present and voting at the meeting legally called for that purpose.
. In the event of a vacancy in the pastoral office, the Church Council shall provide for interim pastoral service.
. If in the judgment of the congregation the pastor is no longer able to serve it satisfactorily, the pastor may be requested to resign. Before the resignation is requested, all parties, including the pastor, shall have the opportunity of being heard at a specially called meeting of the Church Council. After the hearing before the Church Council a special meeting of the congregation may be called to consider a request for the pastor's resignation. A resolution requesting a pastor's resignation must be adopted by a two-thirds majority ballot vote of those present and voting. Not less than ten days notice of such meeting of a congregation must be given. If the pastor's resignation has been requested in the manner here provided, the pastor shall vacate the office at the time the congregation specifies. Should the pastor fail to do so the Church Council shall declare the pastoral office vacant.
. In the event of alleged defection in doctrine or alleged conduct unbecoming a pastor, the matter shall be handled by the Church Council or a committee appointed thereby.

== ARTICLE IX - MEETINGS OF THE CONGREGATION

. The power and authority of the congregation shall be exercised through the congregational meeting, which shall be called and conducted in conformity with civil laws and the provisions of the constitution and bylaws of the congregation.
. The semi-annual meetings of the congregation shall be held in January and in July. Notice of the meeting shall be given as provided in the bylaws.
. A quorum for any regular or special meeting of the congregation shall be 5% of the voting members.
. A special meeting of the congregation may be called by action of the congregation, by petition of at least ten (10) of the voting members, or by any one of the following: the Church Council, the president of the congregation, or the pastor. Official notice of a special meeting of the congregation shall be in writing and shall be posted conspicuously in the place where the congregation customarily worships. Such notice shall state the time, the place and the purpose of the meeting. It shall be signed by the president and the secretary of the congregation, or by the person or persons who have called the meeting, as authorized by this paragraph. The notice of a special meeting shall also be read at all public services of the congregation held during the tend days preceding the date of the meeting.
. The pastor and president of the Church Council shall be notified of the time and place at which a special meeting of the congregation is to be held.
. Only the business for which a special meeting has been called shall be transacted at the meeting.

== ARTICLE X - OFFICERS, COMMITTEES AND ELDERS

At a special meeting held in May, the congregation shall elect individuals to fill open positions of the Church Council and Board of Elders for the next term beginning the first Sunday of July as follows:

. Vice-President who serves in this capacity for one year and assumes the presidency the following year. During the year of serving as Vice-President, this person may also serve in another council position.
. Secretary for a two year term and is elected in even years.
. Treasurer for a two year term and is elected in odd years.
. and the chairpeople of the following committees for a one year term. The council may decide to combine one or more committees for a particular term. If so, there would be one chairperson for that combined committee with one vote on the council:
.. Elders
.. Outreach/Mission
.. Worship
.. Education
.. Stewardship
.. Property
.. Fellowship
. Elders for two year terms. The number to serve as elder will vary with the size of the congregation as indicated in the bylaws.

No person shall be eligible to serve in the same capacity on the Church Council for more than four (4) successive terms. The duties of the officers and elders of the congregation shall be those provided in the bylaws. The officers of the congregation and the chairpeople of the committees together with the pastor shall constitute the Church Council. The president, the vice-president, and secretary of the congregation shall serve in those same as president, vice-president, and secretary of the Church Council respectively.

== ARTICLE XI - BYLAWS

. The congregation shall adopt such bylaws as may from time to time be necessary. No bylaw may conflict with this constitution.
. Bylaws may be adopted or amended at any legally called and conducted meeting of the congregation by a two-thirds majority vote of those present and voting.

== ARTICLE XII - AMENDMENTS

. The doctrinal basis and the confessional subscription contained in Article II, and this paragraph of Article XII shall be unalterable; and no amendment to this constitution shall conflict therewith.
. A proposed amendment to this constitution shall be:
.. read at a public service of the congregation or mailed to the voting members not less than thirty days before the legally called meeting at which it is to be considered;
.. approved without change at the legally called meeting following its announcement, by a majority vote of those present and voting;
.. ratified without further change at the next semi-annual meeting by a two-thirds vote of those present and voting.
. If a proposed amendment fails of adoption, it may be amended by a majority vote of those present and voting, and adopted without change by a two-thirds majority of those present and voting at the next semi-annual meeting.
. At least once every five (5) years the council shall appoint a constitutional committee consisting of a chairman and four members to review the constitution in consultation with the synod. Any changes felt necessary by the committee are to be brought before the congregation at the next semi-annual meeting.
. At least once every five (5) years the council shall appoint a constitution committee consisting of a chairman and four members to review the constitution in consultation with the synod. Any changes felt necessary by the committee are to be brought before the congregation at the next semi-annual meeting for action as outlined above.

= BYLAWS

== PART I - COMMUNION PARTICIPATION
(Cf. Article II of Constitution)

. This congregation invites all of its members who have been prepared to receive the Sacrament to participate regularly in Holy Communion
. Preparation for Holy Communion will normally be provided for persons as young as ten years of age.
. Participation in Holy Communion shall be open to members of other congregations who accept the Lutheran teaching in regard to this Sacrament.
. It shall be made known to prospective participants that the belief of this congregation is: Participation in the Lord's Supper is the reception of "the body and blood of our Lord Jesus Christ given with bread and wine, instituted by Christ himself for us to eat and drink."* We hold that a "person is well prepared and worthy who believes these words, given and shed for you for the remission of sins. But anyone who does not believe these words, or doubts them, is neither prepared nor worthy, for the words for you require simply a believing heart"* +
*From _The Small Catechism in Contemporary English,_ +
(C) 1968 Augsburg Publishing House and Fortress Press.
. Record of participation in Holy Communion shall be maintained. If a member of another congregation communes, notice shall be sent to the pastor of that congregation.

== PART II - CONFLICTING LOYALTIES
(Cf. Article II of Constitution)

. While the buildings of the congregation shall be open to all people to share in its worship, instruction, pastoral care, and fellowship, the congregation rejects all fellowship with organizations which are avowedly religious and which practice forms of religion without confessing faith in the Triune God and in Jesus Christ as the eternal Son of God incarnate to be our only Savior from sin, and which thus teach salvation by works.
. Ceremonies of such organizations indicated above shall not be permitted in the buildings or premises of the congregation.

== PART III - MEMBERSHIP
(Cf. Article V of Constitution)

[upperalpha]
. Baptized Members
[arabic, indent=2]
. A child, one or both of whose parents or guardians are members of the congregation shall, upon receiving Baptism, become a baptized member.
. A child, neither of whose parents or guardians is a member of this congregation, shall upon receiving Baptism, become a baptized member of this congregation, unless for good reason the child is to be a baptized member of another congregation, in which case membership shall be transferred to that congregation.
. A child baptized in another congregation shall be received as a baptized member in the congregation when a transfer has been received.
. An unbaptized adult who has received instruction and has given evidence of an adequate understanding and acceptance of the teachings of the Word of God as confessed by the Lutheran Church, shall, upon confession of faith and Baptism, become a baptized member of the congregation.
. When one or both parents of baptized children are received into the membership of the congregation such children should be received as baptized members with the consent of the member parents or parents.
. When the parents of a baptized child are not themselves members of the Lutheran Church but move into the area served by this congregation and desire to have their child put within the pastoral care of this congregation, the child may be received as a baptized member.

